version: '3.4'

services:
  photogallery.app:
    image: ${DOCKER_REGISTRY-}photogalleryapp
    build:
      context: .
      dockerfile: PhotoGallery.App/Dockerfile

  photogallery.worker:
    image: ${DOCKER_REGISTRY-}photogalleryworker
    build:
      context: .
      dockerfile: PhotoGallery.Worker/Dockerfile

